import Head from "next/head";
import { useEffect, useState } from "react";

type Pizza = {
  id: string;
  name: string;
  amount: number;
  description: string;
  thumbnail_url: string;
};

export default function Home() {
  const [address, setAddresss] = useState<string>("");
  const [username, setUsername] = useState<string>("");
  const [pizzaList, setPizzaList] = useState<Pizza[]>([]);
  const handleClick = () => {
    alert("多分注文できたよ");
  };
  useEffect(() => {
    setPizzaList([
      {
        id: "xxxxxx",
        name: "test",
        amount: 1000,
        description: "test dayo",
        thumbnail_url: "http:/localhost:3000/test.png",
      },
      {
        id: "yyyyyy",
        name: "test2",
        amount: 1000,
        description: "test2 dayo",
        thumbnail_url: "http:/localhost:3000/test.png",
      },
    ]);
  }, []);
  return (
    <>
      <Head>
        <title>Konomi Pizza</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          住所: <input type="text" value={address} />
        </div>
        <div>
          お名前: <input type="text" value={username} />
        </div>
        <div>
          受取方法:{" "}
          <select>
            <option value="0">配達</option>
            <option value="1">お持ち帰り</option>
          </select>
        </div>
        <div>
          ピザ:
          <select>
            {pizzaList.map((pi) => (
              <option key={pi.id} value={pi.id}>
                {pi.name}
              </option>
            ))}
          </select>
        </div>
        <div>
          <button type="button" onClick={handleClick}>
            注文する
          </button>
        </div>
      </div>
    </>
  );
}
